# Generated by Django 4.1 on 2022-08-28 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_character'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Legs',
            new_name='Leg',
        ),
    ]
