# Generated by Django 4.1 on 2022-08-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_legs_leg'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='amulet',
            field=models.ManyToManyField(to='main_app.amulet'),
        ),
        migrations.AddField(
            model_name='character',
            name='chest',
            field=models.ManyToManyField(to='main_app.chest'),
        ),
        migrations.AddField(
            model_name='character',
            name='helm',
            field=models.ManyToManyField(to='main_app.helm'),
        ),
        migrations.AddField(
            model_name='character',
            name='legs',
            field=models.ManyToManyField(to='main_app.leg'),
        ),
        migrations.AddField(
            model_name='character',
            name='ring_one',
            field=models.ManyToManyField(related_name='ring_one', to='main_app.ring'),
        ),
        migrations.AddField(
            model_name='character',
            name='ring_two',
            field=models.ManyToManyField(related_name='ring_two', to='main_app.ring'),
        ),
        migrations.AddField(
            model_name='character',
            name='shield',
            field=models.ManyToManyField(to='main_app.shield'),
        ),
        migrations.AddField(
            model_name='character',
            name='trinket',
            field=models.ManyToManyField(to='main_app.trinket'),
        ),
        migrations.AddField(
            model_name='character',
            name='weapon_one',
            field=models.ManyToManyField(related_name='weapon_one', to='main_app.weapon'),
        ),
        migrations.AddField(
            model_name='character',
            name='weapon_two',
            field=models.ManyToManyField(related_name='weapon_two', to='main_app.weapon'),
        ),
        migrations.AlterField(
            model_name='amulet',
            name='img_URL',
            field=models.CharField(max_length=48),
        ),
        migrations.RemoveField(
            model_name='character',
            name='profile',
        ),
        migrations.AlterField(
            model_name='chest',
            name='img_URL',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='helm',
            name='img_URL',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='leg',
            name='img_URL',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='ring',
            name='img_URL',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='shield',
            name='img_URL',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='trinket',
            name='img_URL',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='img_URL',
            field=models.CharField(max_length=48),
        ),
        migrations.AddField(
            model_name='character',
            name='profile',
            field=models.ManyToManyField(to='main_app.profile'),
        ),
    ]
