# Generated by Django 4.1 on 2022-08-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_character_amulet_character_chest_character_helm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amulet',
            name='critical_damage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='chest',
            name='critical_damage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='helm',
            name='critical_damage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='leg',
            name='critical_damage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ring',
            name='critical_damage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='shield',
            name='critical_damage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trinket',
            name='critical_damage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='critical_damage',
            field=models.FloatField(),
        ),
    ]
